config/routes.rb
Rails.application.routes.draw do
  resources :positions
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get   'fix_basic_info'
      
      get  'attendances/month_checker'
      get  'comfirmation'
      patch 'attendances/update_total_month'
     
     
    end
    collection { post :import } 
    collection do
      get 'employees_on_duty'
      
    end
    
   
   
    resources :attendances, only: [:edit, :update] do
      member do  
        get 'overtime_request'
        patch 'update_overtime'
         
       
      end
      collection do
        get 'overtime_request_info'
        patch 'update_overtime_request_info'
     
        get 'month_request'
        patch 'update_month_request'
     
        get 'approval_month'
        patch 'update_approval_month'
        
        get 'log_page'
        
      end  
     
      
    end   
  end
end 

app/models/position.rb
class Position < ApplicationRecord
     validates :place_num, uniqueness: true, allow_blank: true
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
     @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)
     if @position.save
       flash[:success] = '作成に成功しました。'
       redirect_to positions_url
     else
      flash[:danger] = "拠点情報を追加に失敗しました。"
      redirect_to positions_url   
     end
  end
   

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    @position = Position.find(params[:id])
    if @position.update_attributes(position_params)
       flash[:success] = "拠点情報を更新しました。"# 更新に成功した場合の処理を記述します。
       redirect_to positions_url
    else
      flash[:danger] = "拠点情報を追加に失敗しました。"
      redirect_to positions_url
           
    end
  end  
    
    # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    flash[:success] = "拠点地情報を削除しました。"
    redirect_to positions_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit( :place_num, :place_name, :place_status )
    end
end 

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
 <h1>拠点地編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @position, url: position_path(@position), local: true, method: :patch) do |f| %>
      
      
      <%= f.label :"拠点番号", class: "label-signup"%>
      <%= f.number_field :place_num,  class: "form-control" %>

      <%= f.label :"拠点地",class: "label-signup" %>
      <%= f.text_field :place_name,  class: "form-control" %>
      
      <%= f.label :"拠点種類",class: "label-signup" %>
      <%= f.select :place_status, ['出勤','退勤'], class: "form-control" %>

      <%= f.submit "更新", class: "btn btn-primary btn-block btn-user--edit" %>
    <% end %>
  </div>
</div>

app/views/positions/index.html.erb
<% provide(:title, '拠点一覧') %>
<div class=center>
  <h1>拠点一覧</h1>
   <table  border=2 width=100%, class="table table-bordered table-condensed user-table">
     <thead>
    　<tr>
    　  <th></th>
    　  <th></th>
    　 <th>拠点番号</th>
    　 <th>拠点地</th>
    　 <th>拠点種類</th>
    　</tr>
  　</thead> 
  　
  　 <tbody>
  　  <% @positions.each do|position| %>   
    　 <tr>
          <td><%= link_to "修正",edit_position_path(position, position[:id]) , class: "btn btn-primary" %></td>
    　     <td><%= link_to "削除" , position, method: :delete , class: "btn btn-primary" %></td>
    　     <td><%= position.place_num %></td>
    　     <td><%= position.place_name %></td> 
          <td><%= position.place_status %></td> 
       </tr>
     <% end %>
     <tr>
       <td><%= link_to "拠点情報の追加", new_position_path, class: "btn btn-primary" %></td>
           
     </tr>   
     
  　</tbody> 
  </table>

app/views/positions/new.html.erb
<h1>拠点地新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @position, local: true) do |f| %>
      <%= f.label :"拠点番号", class: "label-signup"%>
      <%= f.number_field :place_num,  class: "form-control" %>

      <%= f.label :"拠点地",class: "label-signup" %>
      <%= f.text_field :place_name,  class: "form-control" %>
      
      <%= f.label :"拠点種類",class: "label-signup" %>
      <%= f.select :place_status, ['出勤','退勤'], class: "form-control" %>
      
      <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-signup" %>
    <% end %>
  </div>
</div>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>