config/routes.rb
Rails.application.routes.draw do
  resources :positions
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get   'fix_basic_info'
      
      get  'attendances/month_checker'
      get  'comfirmation'
      patch 'attendances/update_total_month'
     
     
    end
    collection { post :import } 
    collection do
      get 'employees_on_duty'
      
    end
    
   
   
    resources :attendances, only: [:edit, :update] do
      member do  
        get 'overtime_request'
        patch 'update_overtime'
         
       
      end
      collection do
        get 'overtime_request_info'
        patch 'update_overtime_request_info'
     
        get 'month_request'
        patch 'update_month_request'
     
        get 'approval_month'
        patch 'update_approval_month'
        
        get 'log_page'
        
      end  
     
      
    end   
  end
end 

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
 
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true 
 
  validates :affiliation, length: { in: 2..50 }, allow_blank: true
  validates :employee_number, uniqueness: true, allow_blank: true
  VALID_UID_REGEX =  /\A[a-z0-9]+\z/i
  validates :uid, presence: true, length: { in: 1..10 },
                    uniqueness: true 
  validates :basic_work_time, presence: true
  has_secure_password 
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

   # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      #IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      #CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      #保存する
      user.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation" ,"employee_number", "uid", "basic_work_time", "designated_work_start_time", "superior", "admin", "password"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :comfirmation, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:edit, :update, :destroy, :edit_basic_info, :update_basic_info, :overtime_request]
  before_action :correct_user, only: [:edit, :update, :show]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show  
  before_action :admin_or_correct_user, only: [:index, :show]
   
  def index
    @users = User.where.not(id: 1)
  end
  
  def import
    # fileはtmpに自動で一時保存される
     if params[:csv_file] .blank?
      flash[:danger]= "csvファイルを選択してください"
      redirect_to users_url
     else    
      User.import(params[:csv_file])
      flash[:success]= "インポートしました"
      redirect_to users_url
     end  
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    @request_sum = Attendance.where(superior: @user.name).where(status: "申請中").count
    @change_sum =  Attendance.where(month_check_superior: @user.name).where(month_status: "申請中").count
    @total_superiors =  User.where(superior: true).where.not(id: @user.id)
    @total_month_sum =  Attendance.where(total_month_superior: @user.name).where(total_month_status: "申請中").count
    
    # csv出力
    respond_to do |format|
      format.html 
      format.csv do
        send_data render_to_string, filename: "勤怠一覧表.csv", type: :csv    #csv用の処理を書く
      end
    end
  end
  
  def comfirmation
    @user = User.find (params[:id])
    @first_day = params[:day].to_date.beginning_of_month
    @last_day = @first_day.end_of_month
    @attendances = @user.attendances.where(worked_on: @first_day..@last_day)
    @status_sum = Attendance.where(status: "申請中").count
    @worked_sum = @attendances.where.not(started_at: nil).count
  end  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
       log_in @user # 保存成功後、ログインします。
       flash[:success] = '新規作成に成功しました。'
       redirect_to @user
    else
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end
   
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
   
  def edit_basic_info
  end
   
  def update_basic_info
   if @user.update_attributes(basic_info_params)
       flash[:success] = "#{@user.name}の基本情報を更新しました。"  
   else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
   end
      redirect_to users_url
  end
   
  def employees_on_duty
    @users = User.joins(:attendances).where.not(attendances: {started_at: nil}).where(attendances:{finished_at: nil})
  end
       
   
   


  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :password, :password_confirmation, 
      :employee_number, :uid, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end
    
    def basic_info_params
      params.require(:user).permit( :email,:affiliation,  :password, :password_confirmation, 
      :employee_number, :uid, :basic_time, :work_time, :basic_work_time, :designated_work_start_time, 
      :designated_work_end_time)
    end
    
   
    
    # アクセスしたユーザーが現在ログインしているユーザーか確認します。
    def correct_user
      
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to root_url unless current_user.admin?
    end  
end

app/helpers/users_helper.rb
module UsersHelper
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
 
 
  def format_overtime(overtime, end_time, next_day)
    if next_day == true
        format("%.2f", (overtime.hour - end_time.hour) + (((((overtime.min - end_time.min) /15) *15 )/ 60.0)) + 24)
    else
        format("%.2f", (overtime.hour - end_time.hour) + (((((overtime.min - end_time.min) /15) *15 )/ 60.0)))
    end
  end

end 

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>


 
    
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: user, url: update_basic_info_user_path(user), method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :name, class: "form-control" %>

            <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :affiliation, class: "form-control" %>
            
            <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
            <%= f.number_field :employee_numbe, class: "form-control" %>
            
            <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :uid, class: "form-control" %>
            
            <%= f.label :password, class: "label-#{yield(:class_text)}" %>
            <%= f.password_field :password, class: "form-control" %>

            <%= f.label :password_confirmation,  class: "label-#{yield(:class_text)}" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
  
            <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_work_time, class: "form-control" %>

            <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :designated_work_start_time, class: "form-control" %>
            
            <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :designated_work_end_time, class: "form-control" %>

          
              <%= f.submit :更新, class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" >
                キャンセル
              </button>
          <% end %>
         
        </div>
      </div>
   

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_textr)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>
  
  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation,  class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_position.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">編集</h1>
    </div>
    <div class="modal-body">
     <table  border=2 width=100%, class="table table-bordered table-condensed user-table">
        <thead>
       　<tr>
       　 <th>拠点番号</th>
      　 <th>拠点地</th>
      　 <th rowspan="2">拠点種類</th>
      　</tr>
      </thead> 

app/views/users/comfirmation.html.erb
<% provide(:title, @user.name) %>
<div>
   <table  border=2 width=100%, class="table table-bordered table-condensed user-table">
    <tr>
      <td><%= link_to "⇦", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
         【<%= l(@first_day, format: :middle) %>】時間管理表
          <%=link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-info" %>
      </td>
      <td>指定勤務開始時間：<%= l(@user.designated_work_start_time ,format: :convinient_time) %><br>
          指定勤務終了時間：<%= l(@user.designated_work_end_time ,format: :convinient_time) %>
          
 　    </td>
      <td colspan=3>基本時間：<%= format_basic_info(@user.basic_work_time) %></td>
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>コード</td>
      <td ><%= @user.employee_number %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締め：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div>
  <table border=2 width=100%, class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
     <tr>
       <th rowspan=3></th>
       <th rowspan="3"><br>日付</th>
       <th rowspan="3"><br>曜日</th>
       <th colspan="3"></th>
       <th colspan="8">実績</th>
       <th colspan="5">所定外勤務</th>
     </tr>
     
     <tr>
       <th colspan="3">出社</th>
       <th colspan="3">退社</td>
       <th rowspan="2"><br>在社時間</th>
       <th rowspan="2"><br>備考</th>
       <th colspan="2">終了予定時間</th>
       <th rowspan="2"><br>時間外時間</th>
       <th rowspan="2"><br>勤務処理内容</th>
       <th rowspan="2"><br>指示者確認</th>
     </tr>  
     
      <tr>
        
          <th>時</th>
          <th>分</th>
          <th>   </th>
          <th>時</th>
          <th>分</th>
          <th>   </th>
          <th>時</th>
          <th>分</th>
          
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <% 
          css_class = 
          case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
          when '土'
            'text-primary'
          when '日'
            'text-danger'
          end
         %>
       <tr>
        <td>
          
        </td> 
        <td><%= l(day.worked_on, format: :short) %></td>
        <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
        <td><%= format_hour(day.started_at) if day.started_at.present? %></td>
        <td><%= format_min(day.started_at) if day.started_at.present? %></td>    
        <td>
          <!--< % if btn_text = attendance_state(day) %>-->
            <!--< %= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>-->
          <!--< % end %>-->
        </td>
        <td><%= format_hour(day.finished_at) if day.finished_at.present? %></td>
        <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
        <td></td>
      
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <%= str_times = working_times(day.started_at, day.finished_at) %>
            <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
          <% end %>
        </td>
        <td><%= day.note %></td>
        <td><%= format_hour(day.overtime) if day.overtime.present? %></td>
        <td><%= format_min(day.overtime) if day.overtime.present? %></td>
        <td><%= format_overtime(day.overtime, @user.designated_work_end_time, day.next_day) if day.overtime.present? %></td>
        <td><%= day.task_menu %></td>
        <td><% if day.status == "申請中" %>
        　     <div><%= day.superior %>に残業申請中</div> 
            <% elsif day.status ==  "承認" %> 
              <div> 残業承認済 </div> 
            <% elsif day.status == "否認" %> 
              <div> 残業否認</div>
            <% else %>
              <%= day.status %>
            <% end %> 
        </td> 
        </tr>
     <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="6">総合勤務時間</td>
        <td colspan="4">累計在社時間</td>
        <td></td>
        <td></td>
        <td></td>
        <td rowspan="2">
          <p>所属長未</p><br>
          <select id="page_name" name="page[name]">
          <option value="1">上長A</option>
          <option value="2">上長B</option>
　　　　　</select><br>
　　　　  <div><%= link_to "申請", '#' , class: "btn btn-primary btn-block" %></div>
　　　  </td>　　
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="6"><%= format_basic_info(@user.basic_work_time).to_f * @worked_sum %></td>
        <td colspan="4"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td></td>
        <td></td>
        <td></td>
        </tfoot>    
  </table>
</div>        

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user-edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div id="demo" class="collapse">

  <h1>>基本情報編集</h1>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :affiliation, class: "form-control" %>
            
            <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :employee_number, class: "form-control" %>
            
            <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :uid, class: "form-control" %>
            
            <%= f.label :password, class: "label-#{yield(:class_text)}" %>
            <%= f.password_field :password, class: "form-control" %>

            <%= f.label :password_confirmation,  class: "label-#{yield(:class_text)}" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
  
            <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_work_time, class: "form-control" %>

            <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :designated_work_start_time, class: "form-control" %>
            
            <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :designated_work_end_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
  </div> 

app/views/users/fix_basic_info.html.erb
<div class="center"></div>　　
  <h1>システム全体の基本情報設定ページ</h1> 
  <h1>現在未実装</h1> 
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <h1>ユーザーの個人情報</h1>
  
  <table  border=2 width=100%, class="table table-bordered table-condensed user-table">
    <tr>
      <td><%= link_to "⇦", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
         【<%= l(@first_day, format: :middle) %>】時間管理表
          <%=link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-info" %>
      </td>
      <td>指定勤務開始時間：<%= l(@user.designated_work_start_time ,format: :convinient_time) %><br>
          指定勤務終了時間：<%= l(@user.designated_work_end_time, format: :convinient_time) %>
      </td>
      <td colspan=3>基本時間：<%= format_basic_info(@user.basic_work_time) %></td>
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>コード</td>
      <td ><%= @user.employee_number %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締め：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>
　<% if @user.superior? %>
    <div>
      <% if  @total_month_sum > 0 %>
        <p><font color="red">
         <%= link_to "【所属長承認申請のお知らせ】", approval_month_user_attendances_path(@user), remote: true, style: "color:red;" %>
        <span class="box"><%= @total_month_sum %> 件のお知らせがあります</span></font></p>
      <% else %>
        <p>【所属長承認申請のお知らせ</p>
      <% end %>
    </div>
    <div>
      <% if @change_sum > 0 %>
        <p><font color="red">
         <%= link_to "【勤怠申請変更のお知らせ】", month_request_user_attendances_path(@user), remote: true, style: "color:red;" %>
        <span class="box"><%=  @change_sum %> 件のお知らせがあります</span></font></p>
      <% else %>
        <p>【勤怠申請変更のお知らせ】</p>
      <% end %>
    </div> 
    <div>
      <% if @request_sum > 0 %>
        <p><font color="red">
         <%= link_to "【残業申請のお知らせ】",  overtime_request_info_user_attendances_path(@user), remote: true, style: "color:red;" %>
        <span class="box"><%=  @request_sum %> 件のお知らせがあります</span></font></p>
      <% else %>
        <p>【残業申請のお知らせ】</p>
      <% end %>
    </div> 
  <% end %>
<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", user_path(format: :csv), class: "btn btn-primary" %><br>
  <%= link_to "勤怠修正ログ（承認済）", log_page_user_attendances_path(@user), remote: true, class: "btn btn-primary" %>
</div>


<div>
 
  <table border=2 width=100%, class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
     <tr>
       <th rowspan=3></th>
       <th rowspan="3"><br>日付</th>
       <th rowspan="3"><br>曜日</th>
       <th colspan="3"></th>
       <th colspan="8">実績</th>
       <th colspan="5">所定外勤務</th>
     </tr>
     
     <tr>
       <th colspan="3">出社</th>
       <th colspan="3">退社</td>
       <th rowspan="2"><br>在社時間</th>
       <th rowspan="2"><br>備考</th>
       <th colspan="2">終了予定時間</th>
       <th rowspan="2"><br>時間外時間</th>
       <th rowspan="2"><br>勤務処理内容</th>
       <th rowspan="2"><br>指示者確認㊞</th>
     </tr>  
     
      <tr>
        
          <th>時</th>
          <th>分</th>
          <th>   </th>
          <th>時</th>
          <th>分</th>
          <th>   </th>
          <th>時</th>
          <th>分</th>
          
      </tr>
    </thead>

     
    <tbody>
      <% @attendances.each do |day| %>
        <% 
          css_class = 
          case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
          when '土'
            'text-primary'
          when '日'
            'text-danger'
          end
         %>
       <tr>
        <td>
          <%= link_to "残業申請",  overtime_request_user_attendance_path(@user, day), remote: true, class: "btn btn-primary" %>
        </td> 
        <td><%= l(day.worked_on, format: :short) %></td>
        <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
        <td><%= format_hour(day.started_at) if day.started_at.present? %></td>
        <td><%= format_min(day.started_at) if day.started_at.present? %></td>  
        <td>
          <% if btn_text = attendance_state(day) %>
            <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
          <% end %>
        </td>
        <td><%= format_hour(day.finished_at) if day.finished_at.present? %></td>
        <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
        <td></td>
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <%= str_times = working_times(day.started_at, day.finished_at) %>
          <% elsif day.restarted_at.present? && day.refinished_at.present? %> 
            <%= str_times = format_re_working_times(day.restarted_at, day.refinished_at, day.change_next_day) %>
          <% end %>
          <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
        </td>
        <td><%= day.note %></td>
        <td><%= format_hour(day.overtime) if day.overtime.present? %></td>
        <td><%= format_min(day.overtime) if day.overtime.present? %></td>
        <td><%= format_overtime(day.overtime, @user.designated_work_end_time, day.next_day) if day.overtime.present? %></td>
        <td>
          <%= day.task_menu %><br>
          <%= day.note if day.note.present? %>
         </td>  
        <td><% if day.status == "申請中" %>
        　     <div><%= day.superior %>に残業申請中</div> 
            <% elsif day.status ==  "承認" %> 
              <div> 残業承認済 </div> 
            <% elsif day.status == "否認" %> 
              <div> 残業否認</div>
            <% else %>
              <%= day.status %>
            <% end %> 
        </td> 
        </tr>
      
     <% end %>
    </tbody>
      
                                   
    <tfoot> 
       <tr>
        <td colspan="2"></td>
        <td colspan="6"></td>
        <td></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="5"></td>
        <td>
          <%= form_with(model: @user, url: attendances_update_total_month_user_path(@user), local: true, method: :patch) do |f| %> 
            <%= f.hidden_field :total_month_status, :value => "申請中" %>     
            <%= f.hidden_field :worked_on, :value => @last_day %>  
            <div>所属長承認 未</div>
            <div><%= f.collection_select :total_month_superior, @total_superiors, :name, :name, :include_blank => true, class:  "form-onntrol input-lg" %></div>
            <%= f.submit "申請",  class: "btn btn-primary btn-block" %>
         <% end %>    
        </td>
  　　　</tr>
    </tfoot> 
    
  </table>
 
</div>

<!--モーダルウインドウ表示-->

<div id="overtime-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="overtime-request-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="month-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="log-page" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="approval-month" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>