config/routes.rb
Rails.application.routes.draw do
  resources :positions
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get   'fix_basic_info'
      
      get  'attendances/month_checker'
      get  'comfirmation'
      patch 'attendances/update_total_month'
     
     
    end
    collection { post :import } 
    collection do
      get 'employees_on_duty'
      
    end
    
   
   
    resources :attendances, only: [:edit, :update] do
      member do  
        get 'overtime_request'
        patch 'update_overtime'
         
       
      end
      collection do
        get 'overtime_request_info'
        patch 'update_overtime_request_info'
     
        get 'month_request'
        patch 'update_month_request'
     
        get 'approval_month'
        patch 'update_approval_month'
        
        get 'log_page'
        
      end  
     
      
    end   
  end
end 

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
 
  validate :refinished_at_is_invalid_without_a_restarted_at
  validate :restarted_at_than_refinished_at_fast_if_invalid
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at 
    end
  end
  
  def refinished_at_is_invalid_without_a_restarted_at
    errors.add(:restarted_at, "が必要です") if restarted_at.blank? && refinished_at.present?
  end
 
 
  def restarted_at_than_refinished_at_fast_if_invalid
    if restarted_at.present? && refinished_at.present?
      errors.add(:restarted_at, "より早い退勤時間は無効です") if restarted_at > refinished_at && change_next_day == "0"
    end
  end 


end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: :edit_one_month

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      
      end
    end
    redirect_to @user
  end

  def edit_one_month
    @change_superiors =  User.where(superior: true).where.not(id: @user.id)
  end

 
  def update_one_month
    
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      attendances_params.each do |id, item|
      @attendances = Attendance.find(id)
        if item[:month_check_superior].present? #指示者が選択
           #指示者を選択している場合
          if item[:restarted_at].blank? && item[:refinished_at].present?
            flash[:danger] = "出社時間がないので無効です"
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          elsif item[:restarted_at].present? && item[:refinished_at].blank?
            flash[:danger] = "退社時間がないので無効です"
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          elsif item[:restarted_at].blank? && item[:refinished_at].blank?  
            flash[:danger] = "時間を入力してください"
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          elsif item[:restarted_at].present? && item[:refinished_at].present? && item[:change_next_day] == "0" && item[:restarted_at].to_s > item[:refinished_at].to_s
            flash[:danger] = "入力時間に誤りがあります"
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          elsif item[:note].blank?
            flash[:danger] = "備考欄を記入して下さい。" 
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          end #if end 指示者が選択された場合で、時間が記入されていて成功   
         # @attendance = Attendance.find(id) 
          item[:month_status] = "申請中"
          @attendances.update_attributes!(item)
        elsif item[:month_check_superior].blank? && item[:restarted_at].present? && item[:refinished_at].present? && item[:note].present? 
          flash[:success] = "指示者を選択してください"
          redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
        end
      end #each do end
      flash[:success] = "1ヶ月分の勤怠変更を申請しました。"
      redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
    end #Active record トランザクション終了
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
  end #ef end 
 
 #1か月分の変更申請モーダル 
  def month_request
    @user = User.find(params[:user_id])
    @month_check_superiors =  User.where(superior: true).where.not(id: @user.id)
    @month_requesters = Attendance.where(month_check_superior: @user.name, month_status: "申請中").order(:user_id).group_by(&:user_id)
  end  
  
  #1か月分の勤怠変更承認モーダルupdate
  def update_month_request
    
    @user = User.find(params[:user_id])
    ActiveRecord::Base.transaction do 
      month_request_params.each do |id, item|
        attendance = Attendance.find(id)
        if item[:month_checker] == "1" 
          if item[:month_status] == "承認"
            if attendance.before_change_started == nil
              attendance.before_change_started = attendance.started_at
            end
            if attendance.before_change_finished == nil
              attendance.before_change_finished = attendance.finished_at
            end
            attendance.started_at = attendance.restarted_at
            attendance.finished_at = attendance.refinished_at
            item[:month_update] = Date.today
          end 
          attendance.update_attributes!(item)
          @approval_sum =  Attendance.where(month_status: "承認").count
          @unapproval_sum =  Attendance.where(month_status: "否認").count
          @no_reply =  Attendance.where(month_status: "なし").count
          flash[:success] = "なし#{@no_reply}件、承認#{@approval_sum}件、否認#{@unapproval_sum}件"
        else  
          flash[:danger] = "チェックを記入して下さい。更新をキャンセルしました。"
        end
      end
      redirect_to user_url(@user)
    end
      
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "変更更新をキャンセルしました。"
    redirect_to user_url(@user)
  end
  
  def overtime_request #残業申請
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    @superiors =  User.where(superior: true).where.not(id: @user.id)
  end  

  

  def update_overtime#残業申請アップデート
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    
     # 更新失敗時の処理.
    if params[:attendance]["overtime(4i)"].blank? || params[:attendance]["overtime(5i)"].blank?      
      flash[:danger] = "#{@user.name}の残業時間を選択してください。 "
    elsif params[:attendance][:superior].blank?
      flash[:danger] = "#{@user.name}の指示者を選択して下さい。 "
    else
      params[:attendance][:status] = "申請中"
      @attendance.update_attributes(overtime_params)
      flash[:success] = "#{@user.name}の残業申請をしました。"
    end 
    redirect_to user_url(@user)
  end  
  
  
  #申請モーダル      
  def overtime_request_info 
     @user = User.find(params[:user_id])
     @requesters = Attendance.where(superior: @user.name, status: "申請中").order(:user_id).group_by(&:user_id)
  end 
  
  
  #申請一覧モーダルのupdate
  def update_overtime_request_info
    @user = User.find(params[:user_id])
    ActiveRecord::Base.transaction do 
      overtime_request_info_params.each do |id, item|
        if item[:superior_checker] == "1"
          attendance = Attendance.find(id)
          attendance.update_attributes!(item)
           @info_sum = Attendance.where(status: "承認").count
           @unapproval_info_sum = Attendance.where(status: "否認").count
           @no_reply_info = Attendance.where(status: "なし").count
           flash[:success] = "なし#{@no_reply_info}件、承認#{@info_sum}件、否認#{@unapproval_info_sum}件"
        end #if end 
      end #each end 
      redirect_to user_url(@user)
    end #Acctive do end    
  
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
  flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
  end #def end
  
  def update_total_month
    @user = User.find(params[:id])
    @attendance = @user.attendances.find_by(worked_on: params[:user][:worked_on])
    if params[:user][:total_month_superior].blank?
      flash[:danger]= "所属長を選択してください。"
    else    
      @attendance.update_attributes!(total_month_params)
      flash[:success] = "#{@user.name}の1か月分の申請をしました。"
    end 
    redirect_to user_url(@user)
  end     
 
 
  def approval_month
     @user = User.find(params[:user_id])
     @total_superiors =  User.where(superior: true).where.not(id: @user.id)
     @approval_requesters = Attendance.where(total_month_superior: @user.name, total_month_status: "申請中").order(:user_id).group_by(&:user_id)
  end
  
  
  def update_approval_month
    @user = User.find(params[:user_id])
    ActiveRecord::Base.transaction do
      approval_params.each do |id, item|
        if item[:total_month_checker] == "1"
           attendance = Attendance.find(id)
           attendance.update_attributes!(item)
           @approval_sum2 = Attendance.where(total_month_status: "承認").count
           @unapproval_sum2 = Attendance.where(total_month_status: "否認").count
           @no_reply2 = Attendance.where(total_month_status: "なし").count
           flash[:success] = "なし#{@no_reply2}件、承認#{@approval_sum2}件、否認#{@unapproval_sum2}件"
        else
          flash[:danger] = "チェックを記入して下さい"
        end
      end
    end   
     redirect_to user_url(@user)
    
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
  flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
  end  
  
  def log_page
     @user = User.find(params[:user_id])
     if (params[:year] == nil) || (params[:month] == nil)
        @log_year = Date.today.year
        @log_month = Date.today.month
     elsif (params[:year].present?) && (params[:month].present?)
        @log_year = params[:year]
        @log_month = params[:month]
     end   
     @approvaled = @user.attendances.where(month_status: "承認").order(:worked_on)
     
  end  

  
  
 
      
 
  
  private
    # 1ヶ月分の勤怠情報を扱います。
    def attendances_params
      params.require(:user).permit(attendances: [:restarted_at, :refinished_at, :change_next_day, :note, :month_check_superior, :month_status])[:attendances]
    end
    #overtime(残業申請の内容)の更新カラム
    def overtime_params
      params.require(:attendance).permit(:overtime, :next_day, :task_menu, :superior, :status)
    end
    
    def overtime_request_info_params
      params.require(:user).permit(attendances: [:overtime, :status, :superior_checker])[:attendances]
    end
    
    def month_request_params #1ヶ月分の勤怠変更を扱います。
      params.require(:user).permit(attendances: [:note, :month_status, :month_check_superior, :month_checker, :month_update, :next_day])[:attendances]
    end
    
    def total_month_params #1ヶ月分の勤怠申請を扱います
       params.require(:user).permit(:worked_on, :total_month_superior, :total_month_status)
    end  
    def approval_params 
      params.require(:user).permit(attendances: [:total_month_status, :total_month_checker])[:attendances]
    end
   
    def log_params

app/helpers/attendances_helper.rb
module AttendancesHelper
  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end
  
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
  
  def format_hour(time)
   format("%02d", time.hour)
  end
 
  def format_min(time)
    format("%02d", ((time.min) / 15) * 15)
  end
  
  def format_re_working_times(restart, refinish, change_next_day)
    if change_next_day == true
      format("%.2f",((refinish.hour - restart.hour) + ((((refinish.min - restart.min) /15) * 15) / 60.0)) + 24)
    else
      format("%.2f", (refinish.hour - restart.hour) + ((((refinish.min - restart.min) / 15) * 15) / 60.0))
    end
  end
 
end    

app/views/attendances/_approval_month.html.erb
<% provide(:class_text, 'approval_month') %>
<% provide(:button_text, '1か月分の勤怠申請') %>


<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>  
    <div class="modal-body">
      <%= form_with(model: @user, url: update_approval_month_user_attendances_path(@user), local: true, method: :patch) do |f| %> 
        <%  @approval_requesters.each do |user_id, attendances| %>
          <h1 class="modal-title">【<%= "#{User.find(user_id).name}" %>からの1か月分勤怠申請】</h1>
          <table  border=2 width=100%, class="table table-bordered table-condensed user-table">
            <thead>
              <tr>
                <th>月</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
            
            <% attendances.each do |day| %>
              <%= f.fields_for "attendances[]", day do |at| %>
                <tbody>
                  <tr>
                    <td><%= l(day.worked_on, format: :month) %></td>
                    <td><%= at.select :total_month_status, ['', 'なし', '申請中', '承認', '否認'], class: "form-control" %></td>
                    <td><%= at.check_box :total_month_checker %></td>
                    <td><%= link_to "確認",  comfirmation_user_path(user_id, day: day.worked_on), method: :get, class: "btn btn-primary btn-lg btn-block" %></td>
                  </tr>
                </tbody>
              <% end %>
            <% end %>
          </table> 
       <% end %>
       <%= f.submit "1か月分を承認",  class: "btn btn-primary btn-lg btn-block" %>
     <% end %>
    </div>
  </div>
</div>  

app/views/attendances/_log_page.html.erb
<% provide(:class_text, 'log-page') %>
<% provide(:button_text, '勤怠修正ログ（承認済)' ) %>
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    
    <div class="modal-body">
      <h1 class="modal-title">【勤怠ログ】</h1>
      <%= form_with(url: log_page_user_attendances_path(@user), remote: true, method: :get) do |f| %>
        <table border=2 width=30%, class="table table-bordered table-condensed user-table">
          <tr>
            <td width="10%"><%= f.submit "リセット",  class: "btn btn-default btn-block"%></td>
          </tr>
          <tr>
            <td width="10%">年</td>　
            <td width="50%"><%= f.select :year, (Date.today.year-5)..(Date.today.year+5), :selected => Time.current.year %></td>
          </tr>　　　　　　　　　　　　　　　　　 
          <tr>
            <td width="10%">月</td>
            <td width="60"><%= f.select :month, 1..12, :selected => Date.today.month %></td>
          </tr>
        </table>    
      <% end %>
      <table border=2 width=100%, class="table table-bordered table-condensed user-table">
        <thead>
          <tr> 
             <th>日付</th>
             <th>変更前出社時間</th>
             <th>変更前退社時間</th>
             <th>変更後出社時間</th>
             <th>変更後退社時間</th>
             <th>指示者</th>
             <th>承認日</th>
           </tr>
        </thead>
        
        <tbody>
          <% @approvaled.each do |day| %>
            <% if day.worked_on.year.to_i == @log_year.to_i && day.worked_on.month.to_i == @log_month.to_i %>
              <tr>
                <td><%= day.worked_on %></td>
                <td><%= l(day.before_change_started, format: :convinient_time) if day.before_change_started.present? %></td>
                <td><%= l(day.before_change_finished, format: :convinient_time) if day.before_change_finished.present? %></td>
                <td><%= l(day.started_at, format: :convinient_time)if day.started_at.present? %></td>
                <td><%= l(day.finished_at, format: :convinient_time) if day.finished_at.present? %></td>
                <td><%= day.month_check_superior %></td>
                <td><%= day.month_update %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>  
  </div>
</div>
 

app/views/attendances/_month_request.html.erb
<% provide(:class_text, 'month-request') %>
<% provide(:button_text, '1か月の変更申請') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>  
    <div class="modal-body">
      <%= form_with(model: @user, url: update_month_request_user_attendances_path(@user), local: true, method: :patch) do |f| %> 
        <% @month_requesters.each do |user_id, attendances| %>
          <h1 class="modal-title">【<%= "#{User.find(user_id).name}" %>から勤怠変更申請】</h1>
            <table border=2 width=100%, class="table table-bordered table-condensed user-table">
              <thead>
                <tr>
                  <th rowspan = "2">日付</th>
                  <th rowspan = "2">曜日</th>
                  <th colspan = "2">変更前</th>
                  <th colspan = "2">変更後</th>
                  <th rowspan = "2">備考</th>
                  <th rowspan = "2">指示者確認㊞</th>
                  <th rowspan = "2">変更</th>
                  <th rowspan = "2">勤務を確認する</th>
                </tr>
                <tr>
                  <th>出社</th>
              　   <th>退勤</th>
              　   <th>出社</th>
              　   <th>退勤</th> 
              　</tr>
              </thead>
              <% attendances.each do |day| %>
                <%= f.fields_for "attendances[]", day do |at| %>
                  <tbody>
                    <% 
                      css_class = 
                      case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
                      when '土'
                        'text-primary'
                      when '日'
                        'text-danger'
                      end
                    %> 
                   <tr>
                      <td><%= l(day.worked_on, format: :short) %></td>
                      <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
                      <td><%= l(day.started_at, format: :convinient_time ) if day.started_at.present? %></td>
                      <td><%= l(day.finished_at, format: :time) if day.finished_at.present? %></td>  
                      <td><%= l(day.restarted_at, format: :convinient_time) %> </td>
                      <td><%= l(day.refinished_at, format: :convinient_time) %></td>
                      <td><%= at.text_field :note, class: "form-control" %></td>
                      <td><%= at.select :month_status, ['', 'なし', '申請中', '承認', '否認'], class: "form-control" %></td>
                      <td><%= at.check_box :month_checker %></td>
                      <td><%= link_to "確認", comfirmation_user_path(user_id, day: day.worked_on), method: :get, class: "btn btn-primary btn-lg btn-block" %></td>
                   </tr>  
                  </tbody>
                <% end %>
              <% end %>
           </table>
        <% end %>
      　<%= f.submit "変更を送信する", class: "btn btn-primary btn-lg btn-block" %>
      <% end %> 
    </div>
  </div> 
</div> 

app/views/attendances/_overtime_request_info.html.erb
<% provide(:class_text, 'overtime-request') %>
<% provide(:button_text, '残業申請一覧') %>


<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>  
    <div class="modal-body">
      <%= form_with(model: @user, url: update_overtime_request_info_user_attendances_path(@user), local: true, method: :patch) do |f| %> 
        <% @requesters.each do |user_id, attendances| %>
          <h1 class="modal-title">【<%= "#{User.find(user_id).name}" %>からの残業申請】</h1>
          <table  border=2 width=100%, class="table table-bordered table-condensed user-table">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>指定勤務終了予定時間</th>
                <th>時間外時間</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
            <% attendances.each do |day| %>
              <%= f.fields_for "attendances[]", day do |at| %>
                <tbody>
                   <% 
                    css_class = 
                    case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
                    when '土'
                      'text-primary'
                    when '日'
                      'text-danger'
                    end
                  %> 
              
                  <tr>
                    <td><%= l(day.worked_on, format: :short) %></td>
                     <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
                    <td><%= l(day.overtime, format: :time) %></td>
                    <td><%= l(User.find(user_id).designated_work_end_time, format: :time) %></td>
                    <td><%= format_overtime(day.overtime, User.find(user_id).designated_work_end_time, day.next_day) %></td>
                    <td><%= day.task_menu %></td>
                    <td><%= at.select :status, ['', 'なし', '申請', '承認', '否認'], class: "form-control" %></td>
                    <td><%= at.check_box :superior_checker %></td>
                    <td><%= link_to "確認", comfirmation_user_path(user_id, day: day.worked_on), method: :get, class: "btn btn-primary btn-lg btn-block" %></td>
                  </tr>  
                </tbody>
              <% end %>  
            <% end %>
          </table>
        <% end %>
        <%= f.submit "変更を申請する",  class: "btn btn-primary btn-lg btn-block" %>
      <% end %> 
    </div>
  </div> 
</div>  
    
      
     
        
            
            
                  
            

app/views/attendances/_total_month_request.html.erb
<% provide(:class_text, 'total_month_request') %>
<% provide(:button_text, '1か月分の勤怠申請') %>


<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>  
    <div class="modal-body">
      <%= form_with(model: @user, url: total_month_request_user_attendances_path(@user), local: true, method: :patch) do |f| %> 
        <% @total_manth_rrequesters.each do |user_id, attendances| %>
          <h1 class="modal-title">【<%= "#{User.find(user_id).name}" %>からの1か月分勤怠申請】</h1>
          <table  border=2 width=100%, class="table table-bordered table-condensed user-table">
            <thead>
              <tr>
                <th>月</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
            
            <% attendances.each do |month| %>
              <%= f.fields_for "attendances[]", month do |at| %>
              <tbody>
                <tr>
                  <td><%= month.worked_on %></td>
                  <td><%= at.select :total_month_status, ['', 'なし', '申請', '承認', '否認'], class: "form-control" %></td>
                  <td><%= at.check_box :total_month_checker %></td>
                  <td><%= link_to "確認", comfirmation_user_path(user_id, month: month.worked_on), method: :get, class: "btn btn-primary btn-lg btn-block" %></td>
                </tr>
              </tbody>
             <% end %>
           <% end %>
          </table> 
        <% end %> 
     <% end %>
    </div>
  </div>
</div>  

app/views/attendances/approval_month.js.erb
$("#approval-month").html("<%= escape_javascript(render 'approval_month') %>");
$("#approval-month").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
<div>
  <h1>勤怠編集画面</h1>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出勤</th>
        <th>退社</th>
        <th>翌日</th>
        <th>在社時間</th>
        <th>備考</th>
        <th>指示者確認㊞</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
       <% 
          css_class = 
          case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
          when '土'
            'text-primary'
          when '日'
            'text-danger'
          end
         %>
       <%= f.fields_for "attendances[]", day do |attendance| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td><%= $days_of_the_week[day.worked_on.wday] %></td>
          <% if !current_user.admin? && (Date.current < day.worked_on) %>
            <td><%= attendance.time_field :restarted_at,  readonly: true, class: "form-control" %></td>
            <td><%= attendance.time_field :refinished_at, readonly: true, class: "form-control" %></td>
          <% else %> 
            <td><%= attendance.time_field :restarted_at, class: "form-control" %></td>
            <td><%= attendance.time_field :refinished_at, class: "form-control" %></td>
          <% end %>    
          <td><%= attendance.check_box :change_next_day %></td>
          <td>
            <% if day.restarted_at.present? && day.refinished_at.present? %>
              <%= str_time = format_re_working_times(day.restarted_at, day.refinished_at, day.change_next_day) %>
              <!--< % @total_working_times = @total_working_times.to_f + str_times.to_f %>-->
            <% end %>
          </td>
          <td><%= attendance.text_field :note, class: "form-control" %></td>
          <td><%= attendance.collection_select :month_check_superior,  @change_superiors, :name, :name, :include_blank => true %></td>
         </tr>
      <% end %>
    <% end %>  
    </tbody>
  </table>
</div>

<div class="center">
  <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
  <%= f.submit "編集を送信する", class: "btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/attendances/log_page.js.erb
$("#log-page").html("<%= escape_javascript(render 'log_page') %>");
$("#log-page").modal("show");

app/views/attendances/month_request.js.erb
$("#month-request").html("<%= escape_javascript(render 'month_request') %>");
$("#month-request").modal("show");

app/views/attendances/overtime_request.js.erb
$("#overtime-request").html("<%= escape_javascript(render 'overtime_request') %>");
$("#overtime-request").modal("show");